### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 742)

### ISSUE THREAD

**Issue by ZainaliSyed** [niftylettuce/react-native-phone-verification#6]
![screenshot from 2017-10-23 11-52-11](https://user-images.githubusercontent.com/24393023/31875722-bf7953bc-b7e8-11e7-8964-e2a0e8a8a534.png)

 UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 742): UnableToResolveError: Unable to resolve module prop-types from /home/********/Downloads/react-native-phone-verification-master/example/node_modules/react-native-emoji/index.js: Module does not exist in the module map or in these directories:
  /home/**********/Downloads/react-native-phone-verification-master/example/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
(node:13747) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled willterminate the Node.js process with a non-zero exit code.

 **I have Follow all these three steps as but still faceing same error .**

**Comment by Mrezagolbaba** [comment]
i have problem when i try running example its my issue

{"type":"internalError","message":"react-packager has encountered an internal error, please check your terminal error output for more details"}

and in my terminal:


Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:682:18)
    at Object.readSync (/Users/mohammadreza/project app/sms/node_modules/graceful-fs/polyfills.js:138:28)
    at tryReadSync (fs.js:543:20)
    at Object.fs.readFileSync (fs.js:586:19)
    at Module._readSourceCode (/Users/mohammadreza/project app/sms/node_modules/metro-bundler/src/node-haste/Module.js:204:29)
    at Module._getCacheProps (/Users/mohammadreza/project app/sms/node_modules/metro-bundler/src/node-haste/Module.js:394:29)
    at Module._readFromTransformCache (/Users/mohammadreza/project app/sms/node_modules/metro-bundler/src/node-haste/Module.js:344:29)
    at Module.readCached (/Users/mohammadreza/project app/sms/node_modules/metro-bundler/src/node-haste/Module.js:331:19)
    at ResolutionRequest.preprocessModule (/Users/mohammadreza/project app/sms/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:324:27)
    at ResolutionRequest._preprocessPotentialDependencies (/Users/mohammadreza/project app/sms/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:308:27)



cloud you please help me!!!!

**Comment by RidaRidss** [comment]
![issue](https://user-images.githubusercontent.com/11027366/39720528-1afc6ef6-5256-11e8-872f-0432542f0260.png)
facing same error

**Comment by ZainaliSyed** [comment]
@RidaRidss  
Try these cache commands  
1. watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf ios/build && rm -rf node_modules && yarn cache clean && npm cache verify
2. yarn install && yarn start --reset-cache
