### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Mrezagolbaba** [niftylettuce/react-native-phone-verification#7]
i have problem when i try running example its my issue

{"type":"internalError","message":"react-packager has encountered an internal error, please check your terminal error output for more details"}

and in my terminal:

Error: EISDIR: illegal operation on a directory, read
at Object.fs.readSync (fs.js:682:18)
at Object.readSync (/Users/mohammadreza/project app/sms/node_modules/graceful-fs/polyfills.js:138:28)
at tryReadSync (fs.js:543:20)
at Object.fs.readFileSync (fs.js:586:19)
at Module._readSourceCode (/Users/mohammadreza/project app/sms/node_modules/metro-bundler/src/node-haste/Module.js:204:29)
at Module._getCacheProps (/Users/mohammadreza/project app/sms/node_modules/metro-bundler/src/node-haste/Module.js:394:29)
at Module._readFromTransformCache (/Users/mohammadreza/project app/sms/node_modules/metro-bundler/src/node-haste/Module.js:344:29)
at Module.readCached (/Users/mohammadreza/project app/sms/node_modules/metro-bundler/src/node-haste/Module.js:331:19)
at ResolutionRequest.preprocessModule (/Users/mohammadreza/project app/sms/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:324:27)
at ResolutionRequest._preprocessPotentialDependencies (/Users/mohammadreza/project app/sms/node_modules/metro-bundler/src/node-haste/DependencyGraph/ResolutionRequest.js:308:27)

cloud you please help me!!!!

**Comment by felansu** [comment]
Try run your IDE as administrator.
